import type { Compilation, Excerpt } from '@/types/compilation';

const lines = [
    'B1 - al-Fawākih al-ʿadhāb fī al-radd ʿalá man lam yaḥkum al-Sunnah wa-al-Kitāb',
    'B2 - al-Nawāzil fī al-Raḍāʿ',
    'B3 - Iʿrāb al-Qirāʾāt al-Sabʿ wa-ʿIlalihā [al-ʿIlmīyah]',
    'B4 - al-Ṭarīq al-Mustaqīm fī Naẓm ʿAlāmāt al-Tarqīm',
    'B5 - Asmāʾ al-Mudallisīn',
    'B6 - Zawāʾid Ibn al-Jawzī ʿalá Muqātil fī al-Wujūh wa-al-Naẓāʾir',
    'B8 - Durūs lil-Shaykh ʿAṭīyah Sālim',
    'B9 - Mukhtaṣar Khawqīr fī Fiqh al-Imām Aḥmad',
    'B10 - Tajrīd al-Qawāʿid wa-al-Fawāʾid al-Uṣūlīyah',
    'B11 - Tawfīq al-Rabb al-Munʿim bi-Sharḥ Ṣaḥīḥ al-Imām Muslim',
    'B12 - Istidrākāt al-Samīn al-Ḥalabī ʿalá Ibn ʿAṭīyah',
    'B13 - Istinbāṭāt al-Samʿānī fī Kitābihi «Tafsīr al-Qurʾān» wa-Manhajuhu fīhā',
    'B14 - Istinbāṭāt al-Shaykh ʿAbd al-Raḥmān al-Saʿdī min al-Qurʾān al-Karīm ʿArḍ wa-Dirāsah',
    'B15 - al-Istinbāṭ ʿinda al-Khaṭīb al-Shirbīnī fī Tafsīrihi al-Sirāj al-Munīr',
    'B16 - Dīwān al-Sunnah - Qism al-Ṭahārah',
    'B17 - Ḥukm al-Taqlīd',
    'B18 - Majmūʿ fīhi Arbaʿ Rasāʾil - al-Ḥajjāwī',
    'B19 - Qawāʿid al-Uṣūl wa-Maʿāqid al-Fuṣūl',
    'B20 - Mukhtaṣar Tuḥfat al-Muḥtāj bi-Sharḥ al-Minhāj',
    'B21 - Tajrīd Aḥādīth ʿUmdat al-Fiqh',
    'B22 - Aʿmār al-Aʿyān',
    'B23 - Sabīl al-Muhtadīn ilá Sharḥ al-Arbaʿīn al-Nawawīyah',
    'B25 - Sīr al-Ḥāthth ilá ʿIlm al-Ṭalāq al-Thalāth [al-Nawādir]',
    'B26 - al-Ikhwah wa-al-Akhawāt - al-Dāraquṭnī',
    'B27 - Akhbār Makkah - al-Fākihī [al-Ṭabʿah al-rābiʿah]',
    'B28 - Tārīkh al-Barzalī al-Muqtafī li-Tārīkh Abī Shāmah - taḥqīq Tadmurī',
    'B29 - Taysīr al-Tafsīr lil-Qaṭṭān',
    'B30 - Qawāʿid Ibn Rajab [Rakāʾiz]',
    'B31 - Iʿrāb al-Qirāʾāt al-Sabʿ wa-ʿIlalihā - taḥqīq al-ʿUthaymīn',
    'B32 - Mukhtaṣar al-Fatāwá al-Miṣrīyah [Rakāʾiz]',
    'B33 - al-Iʿrāb ʿan al-Ḥayrah wa-al-Iltibās al-Mawjūdayn fī Madhāhib Ahl al-Raʾy wa-al-Qiyās',
    'B34 - al-Iʿlān bi-al-Tawbīkh liman Dhamm Ahl al-Taʾrīkh - taḥqīq al-Ẓufayrī',
    'B36 - Lubāb al-Tafāsīr lil-Kirmānī (Nāqiṣ)',
    'B39 - Aḥkām al-Qurʾān li-Bakr ibn al-ʿAlāʾ [Jāʾizat Dubayy]',
    'B40 - Aḥādīth al-ʿAṭṭār ʿan Shuyūkhihi',
    'B41 - Tafsīr al-Baghawī [Ṭaybah]',
    'B42 - Tafsīr al-Saʿdī = Taysīr al-Karīm al-Raḥmān',
    'B43 - Tafsīr al-Ṭabarī Jāmiʿ al-Bayān [Dār al-Tarbiyah wa-al-Turāth]',
    'B44 - al-Inḥirāf al-ʿAqdī fī Adab al-Ḥadāthah wa-Fikrihā',
    'B45 - Badr al-Tamām Sharḥ Lāmīyat Shaykh al-Islām',
    'B46 - al-Masbūk ʿalá Minḥat al-Sulūk fī Sharḥ Tuḥfat al-Mulūk',
    'B47 - al-Jāmiʿ al-Kāmil fī al-Ḥadīth al-Ṣaḥīḥ al-Shāmil al-Murattab ʿalá Abwāb al-Fiqh',
    'B48 - al-Mukhtaṣar min Akhbār Fāṭimah bint Sayyid al-Bashar ṣallá Allāh ʿalayhi wa-ālihi wa-sallam',
    'B49 - Qiṣṣat al-Ḥayāh',
    'B50 - Fāṭimah bint al-Nabī - ṣallá Allāh ʿalayhi wa-sallam - Sīratuhā, Faḍāʾiluhā, Musnaduhā - raḍiya Allāh ʿanhā -',
    'B51 - ʿAqīdat al-Īmān bi-al-Yawm al-Ākhir wa-Atharuhā fī Iṣlāḥ al-Mujtamaʿ',
    'B52 - al-Muḥaddith al-Fāṣil - taḥqīq Abū Zayd',
    'B53 - al-Ightiyālāt',
    'B54 - Manẓūmat al-Ādāb = al-Alfīyah fī al-Ādāb al-Sharʿīyah',
    'B55 - al-Tabārīḥ fī Ṣalāt al-Tarāwīḥ',
    'B56 - al-Tuḥfah al-Nadiyyah Sharḥ al-ʿAqīdah al-Wāsiṭīyah - ʿAbd al-Raḥmān al-ʿAql',
    'B57 - al-Budūr al-Zāhirah fī al-Qirāʾāt al-ʿAshr al-Mutawātirah - ʿAbd al-Fattāḥ al-Qāḍī',
    'B58 - al-ʿAmal bi-al-Aghlabīyah',
    'B59 - Ḥīnamā yaʿtakifu al-Qalb',
    'B60 - Madkhal ilá ʿUlūm al-Sharīʿah',
    'B61 - Majmaʿ al-Zawāʾid wa-Manbaʿ al-Fawāʾid',
    'B62 - al-Masāʾil al-Jaliyyah fī Aḥkām al-Uḍḥīyah',
    'B63 - al-Istighrāb',
    'B64 - al-Māturīdīyah',
    'B65 - al-Mutashābih',
    'B66 - al-Tamadhhub – Dirāsah Naẓarīyah Naqdīyah',
    'B67 - Tafsīr Ibn ʿArafah',
    'B68 - Ḥujaj al-Ashāʿirah al-ʿĀmmah ʿalá mā Nafawhu min al-Ṣifāt wa-al-ʿUluww wa-al-Jawāb ʿan Adillatihim al-ʿAqlīyah',
    'B69 - Dirāsat ʿIlm al-Adyān - Ahammīyatuhā wa-Manāhij al-Bāḥithīn fīhā -',
    'B70 - ʿAqīdat al-Īmān bi-al-Qaḍāʾ wa-al-Qadar ʿinda al-Salaf wa-Atharuhā ʿalá al-Muʾmin',
    'B71 - Tārīkh Dimashq li-Ibn ʿAsākir',
    'B72 - al-Nujūm al-Zāhirāt fī Faḍāʾil al-Bāqiyāt al-Ṣāliḥāt',
    'B73 - Qawāʿid wa-Fawāʾid fī al-Amr bi-al-Maʿrūf wa-al-Nahy ʿan al-Munkar min Kalām Shaykh al-Islām Ibn Taymīyah',
    'B74 - Madhāhib al-Nās fī Ṣifat al-Maḥabbah li-Allāh ʿazza wa-jall',
    'B75 - Manhaj al-Salaf fī al-Difāʿ ʿan al-ʿAqīdah',
    'B76 - Mawqif al-Mustashriqīn min al-Muʿtazilah',
    'B77 - al-Hijrah al-Nabawīyah al-Sharīfah Durūs wa-Fawāʾid wa-Laṭāʾif',
    'B78 - al-Jāmiʿ al-Musnad al-Ṣaḥīḥ',
    'B79 - Ibrām ʿUqūd al-Nikāḥ ʿabra Wasāʾil al-Ittiṣālāt al-Ḥadīthah - Dirāsah Fiqhīyah Ḥadīthīyah',
    'B80 - al-Salāsil al-Mukhtārah min Ṣaḥīḥ al-Imām al-Bukhārī',
    'B81 - Rubāʿīyāt wa-Thumānīyāt al-Imām al-Bukhārī',
    'B82 - Manājim al-Asrār fī Faḍl al-Istighfār',
    'B83 - al-Muḥīṭ fī al-Lughah',
    'B84 - al-Muṣannaf - ʿAbd al-Razzāq [al-Taʾṣīl al-Thāniyah]',
    'B85 - Wa-Aḥfiẓū Aymānakum',
    'B86 - Iʿrāb al-Qurʾān al-Karīm [Dār al-Ṣaḥābah]',
    'B87 - Masāʾil al-ʿIbādāt al-Mukhtaṣṣah bi-al-Zawjayn',
    'B88 - Rawḍat al-Muḥaddithīn',
    'B89 - Ikmāl Tahdhīb al-Kamāl [al-ʿIlmīyah]',
    'B90 - al-Kamāl fī Asmāʾ al-Rijāl',
    'B91 - Sharḥ al-Khurashī ʿalá Mukhtaṣar Khalīl - wa-Maʿahu Ḥāshiyat al-ʿAdawī',
    'B92 - Aḥkām al-Qurʾān lil-Shāfiʿī - Jamʿ al-Bayhaqī, taḥqīq al-Shawāmī',
    'B93 - al-Muṭrib min Ashʿār Ahl al-Maghrib',
    'B94 - al-Qaṣīdah al-ʿAjībah wa-al-Mufradah al-Gharībah Dhāt al-Asʾilah al-Mufḥamah wa-al-Maʿānī al-Muḥkamah',
    'B95 - al-Ṣaḥīḥ min al-Akhbār al-Mujtamaʿ ʿalá Ṣiḥḥatihi - Makhṭūṭ',
    'B96 - Sabīl al-Rashād [al-Ṭabʿah al-thāniyah]',
    'B97 - al-Mūfī bi-Maʿrifat al-Taṣawwuf wa-al-Ṣūfī',
    'B98 - Jāmiʿ al-Waraʿ wa-Qāmiʿ al-Bidaʿ',
    'B99 - al-Mudhakkar wa-al-Muʾannath',
    'B100 - Taʾammulāt fī al-Suwar wa-al-Āyāt',
    'B101 - Tārīkh Ibn Maʿīn - Riwāyat Ibn Miḥraz',
    'B102 - al-Bahjah al-Wafīyah bi-Ḥujjat al-Khulāṣah al-Alfīyah',
    'B103 - al-ʿAtīq Muṣannaf Jāmiʿ li-Fatāwá Aṣḥāb al-Nabī ṣallá Allāh ʿalayhi wa-sallam',
    'B104 - al-Madkhal ilá Ṣaḥīḥ al-Bukhārī',
    'B105 - al-Wafīyah bi-Ikhtiṣār al-Alfīyah',
    'B106 - Bughyat al-Rāʾid limā Taḍammanahu Ḥadīth Umm Zarʿ min al-Fawāʾid - taḥqīq al-Dasūqī',
    'B107 - Fatāwá Nūr ʿalá al-Darb li-Ibn Bāz - bi-ʿInāyat al-Shuwayʿir',
    'B108 - Muntaqá al-Alfāẓ bi-Taqrīb ʿUlūm al-Ḥadīth lil-Ḥuffāẓ',
    'B109 - Taʾammulāt fī Ruʾyā Yūsuf ʿalayhi al-salām',
    'B110 - Dhayl al-ʿIrāqī ʿalá al-ʿIbar',
    'B111 - Dhayl al-Murshidī ʿalá al-ʿIbar',
    'B112 - Dhayl Ibn al-ʿIrāqī ʿalá al-ʿIbar',
    'B113 - al-Tārīkh al-Kabīr lil-Bukhārī - taḥqīq al-Dabbāsī wa-al-Naḥḥāl',
    'B115 - Aṣl al-Zarārī Sharḥ Ṣaḥīḥ al-Bukhārī - Makhṭūṭ',
    'B116 - Ibn Ḥazm wa-Mawqifuhu min al-Ilāhīyāt ʿArḍ wa-Naqd',
    'B117 - Ibn Rajab al-Ḥanbalī wa-Atharuhu fī Tawḍīḥ ʿAqīdat al-Salaf',
    'B118 - Athar al-Istishrāq ʿalá al-Manhaj al-ʿAqdī bi-al-Hind',
    'B119 - al-ʿUrf al-Shadhī Sharḥ Sunan al-Tirmidhī',
    'B120 - Miftāḥ al-Afkār lil-Taʾahhub li-Dār al-Qarār',
    'B121 - Ijmāʿ al-Salaf fī al-Iʿtiqād kamā Ḥakāhu Ḥarb al-Kirmānī',
    'B122 - al-Amākin, mā Ittafaqa Lafẓuhu wa-Iftaraqa Musammāhu',
    'B123 - Aḥādīth al-ʿAqīdah allatī Yūhim Ẓāhiruhā al-Taʿāruḍ fī al-Ṣaḥīḥayn Dirāsah wa-Tarjīḥ',
    'B124 - Aḥādīth al-ʿAqīdah al-Mutawahham Ishkāluhā fī al-Ṣaḥīḥayn Jamʿan wa-Dirāsah',
    'B125 - al-Kawkab al-Munīr fī Sharḥ al-Alfīyah bi-al-Tashṭīr',
    'B126 - al-Kawākib al-Durrīyah ʿalá al-Manẓūmah al-Bayqūnīyah',
    'B130 - al-Ightibāṭ bi-man Rumiy min al-Ruwāt bi-al-Ikhtilāṭ',
    'B131 - Aʿyān al-ʿAṣr wa-Aʿwān al-Naṣr',
    'B132 - Bayān Faḍl ʿIlm al-Salaf ʿalá ʿIlm al-Khalaf',
    'B133 - al-Aḥādīth al-Wāridah fī Faḍāʾil al-Ṣaḥābah',
    'B134 - Ighāthat al-Lahfān fī Ḥukm Ṭalāq al-Ghaḍbān - taḥqīq al-Ḥufayyān',
    'B135 - al-Amthāl - Abū ʿUbayd',
    'B136 - al-Ikhtiyārayn al-Mufaḍḍalīyāt wa-al-Aṣmaʿīyāt',
    'B137 - Fatḥ al-Bārī li-Ibn Rajab',
    'B138 - Shamāʾil al-Ḥabīb al-Muṣṭafā',
    'B139 - al-Ḥawāshī al-Sābighāt ʿalá Akhṣar al-Mukhtaṣarāt',
    'B140 - Dalīl al-Fāliḥīn li-Ṭuruq Riyāḍ al-Ṣāliḥīn',
    'B141 - Madārij Tafaqquh al-Ḥanbalī',
    'B142 - al-Ittiṣāl wa-al-Inqiṭāʿ',
    'B143 - Muqāranat al-Marwīyāt',
    'B144 - al-Taʿrīf bi-al-Islām',
    'B145 - Matn Tashīl al-ʿAqīdah al-Islāmīyah [al-Ṭabʿah al-sādisah]',
    'B146 - al-Ṭabaqāt al-Kubrá [al-Khānjī]',
    'B147 - Min Sharḥ Bulūgh al-Marām lil-Ṭurayfī',
    'B148 - Tārīkh Ibn Maʿīn - Riwāyat al-Dārimī',
    'B149 - Mukhtaṣar Sharḥ Tashīl al-ʿAqīdah al-Islāmīyah [al-Ṭabʿah al-sādisah]',
    'B150 - Akhbār al-Quḍāh',
    'B151 - Sharḥ ʿUmdat al-Fiqh - Ibn Taymīyah [ʿAṭāʾāt al-ʿIlm]',
    'B152 - al-Mashhūr min Asānīd al-Ḥadīth',
    'B153 - al-Qadar - Ibn Wahb - taḥqīq al-Ḥufayyān',
    'B154 - Zahr al-Firdaws = al-Gharāʾib al-Multaqaṭah min Musnad al-Firdaws',
    'B155 - al-Jarḥ wa-al-Taʿdīl - al-Lāḥim',
    'B156 - al-Taḥqīqāt ʿalá Sharḥ al-Jalāl lil-Waraqāt',
    'B157 - Mawsūʿat Aḥkām al-Ṭahārah - al-Dubayyān [al-Ṭabʿah al-thālithah]',
    'B158 - al-Dāʾ wa-al-Dawāʾ = al-Jawāb al-Kāfī [Dār al-Maʿrifah]',
    'B159 - al-Takmilah li-Wafayāt al-Naqalah',
    'B160 - al-Ḥukm bi-Ghayr mā Anzala Allāh - al-Muḥyānī [al-Ṭabʿah 1437]',
    'B161 - Sunan Saʿīd ibn Manṣūr - Takmilat al-Tafsīr [al-Alūkah]',
    'B162 - al-Qaṭārah al-Naḥwīyah ʿalá al-Muqaddimah al-Ājurrūmīyah',
    'B163 - Hadm al-Manārah liman Ṣaḥḥaḥ Aḥādīth al-Tawassul wa-al-Ziyārah',
    'B164 - ʿIṭr al-Majālis - Durūs Qaṣīrah fīmā lā Yanbaghī lil-Muslim Jahluhu',
    'B165 - Fatḥ al-ʿAllām fī Dirāsat Aḥādīth Bulūgh al-Marām [al-Ṭabʿah al-rābiʿah]',
    'B166 - al-Faḍl al-Maʾthūr min Sīrat al-Sulṭān al-Malik al-Manṣūr',
    'B167 - al-Mustamlaḥ min Kitāb al-Takmilah',
    'B168 - Tafsīr Mubhamāt al-Qurʾān',
    'B169 - Maʿa al-Mushakkikīn fī al-Sunnah',
    'B170 - al-Jawāb al-Ṣaḥīḥ li-man Baddala Dīn al-Masīḥ li-Ibn Taymīyah',
    'B171 - Ṣaḥīḥ al-Targhīb wa-al-Tarhīb',
    'B172 - Ṣiḥḥat Naql al-Ijmāʿ ʿinda Shaykh al-Islām fī Ḥurmat al-Ṭawāf bi-Ghayr al-Bayt al-Ḥarām',
    'B173 - Ṣilat al-Takmilah li-Wafayāt al-Naqalah',
    'B174 - Sharḥ al-Fāriḍī ʿalá Alfīyat Ibn Mālik',
    'B175 - Fatḥ al-Shakūr fī Maʿrifat Aʿyān ʿUlamāʾ al-Takrūr',
    'B176 - Ittiʿāẓ al-Ḥunafāʾ bi-Akhbār al-Aʾimmah al-Fāṭimīyīn al-Khulafāʾ',
    'B177 - Miftāḥ al-Wuṣūl ilá ʿIlm al-Uṣūl fī Sharḥ Khulāṣat al-Uṣūl',
    'B178 - Ittibāʿ al-Sunan wa-Ijtināb al-Bidaʿ',
    'B179 - Ḍaʿīf al-Targhīb wa-al-Tarhīb',
    'B180 - al-Manthūr',
    'B181 - Musnad Abī Yaʿlá - taḥqīq al-Sannārī',
    'B182 - Ashrāṭ al-Sāʿah - al-Wābil',
    'B183 - Zawāʾid Tārīkh Baghdād ʿalá al-Kutub al-Sittah',
    'B184 - al-Ṣawāʿiq al-Mursalah ʿalá al-Jahmīyah wa-al-Muʿaṭṭilah [ʿAṭāʾāt al-ʿIlm]',
    'B185 - al-ʿIlal al-Wāqiʿah fī Kitāb al-Jāmiʿ al-Ṣaḥīḥ lil-Bukhārī',
    'B186 - al-Arbaʿīn min Riwāyat al-Muḥammadīn al-Mukhraj Dhālika min Ṣaḥīḥ al-Bukhārī',
    'B187 - al-Aḥādīth al-Miʾah al-Mukhrajah min al-Ṣaḥīḥ al-Musalsalah bi-al-Muḥammadīn',
    'B188 - Taḥqīq Izālat al-Dahsh wa-al-Walah',
    'B189 - Majmaʿ al-Baḥrayn lil-Yāzijī = Maqāmāt al-Yāzijī',
    'B190 - al-Fawāʾid al-Muntaqāh ʿalá Sharṭ al-Imāmayn',
    'B191 - Mā Rawāhu al-Asāṭīn fī ʿAdam al-Majīʾ ilá al-Salāṭīn',
    'B192 - al-Arbaʿūn al-ʿAqdīyah',
    'B193 - al-Ghurar fī Faḍāʾil ʿUmar',
    'B194 - al-Rawḍ al-Anīq fī Faḍl al-Ṣiddīq',
    'B195 - Isrāʾīl wa-al-Talmūd - Dirāsah Taḥlīlīyah',
    'B196 - al-Saʿādah wa-al-Falāḥ fī Fahm Maqāṣid al-Nikāḥ',
    'B197 - Zād al-Maʿād fī Hady Khayr al-ʿIbād [ʿAṭāʾāt al-ʿIlm]',
    'B198 - Iṣlāḥ al-Faqīh Fuṣūl fī al-Iṣlāḥ al-Fiqhī',
    'B199 - Madārij al-Sālikīn [ʿAṭāʾāt al-ʿIlm]',
    'B200 - Asbāb al-Maghfirah',
    'B201 - Tahdhīb Sunan Abī Dāwūd [ʿAṭāʾāt al-ʿIlm]',
    'B202 - Mashyakhat Abī al-Mawāhib al-Ḥanbalī',
    'B203 - Dhayl Lisān al-Mīzān',
    'B204 - al-Majālis al-Fiqhīyah',
    'B205 - Shifāʾ al-ʿAlīl fī Masāʾil al-Qaḍāʾ wa-al-Qadar wa-al-Ḥikmah wa-al-Taʿlīl [ʿAṭāʾāt al-ʿIlm]',
    'B207 - Risālah fī Jamʿ Ashkāl al-Ḥadīth al-Ḍaʿīf',
    'B208 - Ikhtiyārāt al-Qāḍī Abī Yaʿlá al-Ḥanbalī al-Fiqhīyah min Awwal Kitāb al-Ṭahārah ilá Ākhir Bāb al-Tayammum',
    'B209 - Asrār al-Kawn = al-Hayʾah al-Sanīyah fī al-Hayʾah al-Sanīyah',
    'B211 - Fatḥ al-Karīm al-Mannān fī Ādāb Ḥamalat al-Qurʾān',
    'B212 - al-Fawāʾid li-Ibn al-Qayyim [ʿAṭāʾāt al-ʿIlm]',
    'B213 - Buzūgh al-Hilāl fī al-Khiṣāl al-Mūjibah lil-Ẓilāl',
    'B214 - Ṭabaqāt Fuqahāʾ al-Yaman',
    'B215 - al-Taʿrīf bimā Ānasat al-Hijrah min Maʿālim Dār al-Hijrah',
    'B216 - al-Wābil al-Ṣayyib [Dār al-Ḥadīth]',
    'B217 - al-Hilāl - Mashhūr',
    'B218 - Aḥkām Ahl al-Dhimmah [ʿAṭāʾāt al-ʿIlm]',
    'B219 - al-Riʿāyah al-Ṣughrá fī al-Fiqh',
    'B221 - Muʾallafāt Ibn Qayyim al-Jawzīyah - Nusakhuhā al-Khaṭṭīyah wa-Ṭibāʿātuhā',
    'B222 - Tamhīd al-Farsh fī al-Khiṣāl al-Mūjibah li-Ẓill al-ʿArsh',
    'B224 - al-Muʿāraḍāt al-Fikrīyah al-Muʿāṣirah li-Aḥādīth al-Ṣaḥīḥayn',
    'B225 - al-Ḥaqq wa-al-Thabāt fī al-Asmāʾ wa-al-Ṣifāt',
    'B226 - al-Tanbīhāt ʿalá Aghālīṭ al-Ruwāt',
    'B227 - al-Maʿná fī Ṣifāt Allāh Taʿālā Maʿlūm wa-al-Kayf Majhūl',
    'B229 - Tuḥfat al-Mawdūd bi-Aḥkām al-Mawlūd [ʿAṭāʾāt al-ʿIlm]',
    'B230 - Mawsūʿat Tafsīr al-Aḥlām',
    'B231 - Itḥāf al-Anām bi-Aḥkām wa-Masāʾil al-Ṣiyām',
    'B232 - al-Qism al-Thālith min al-Muʿjam al-Awsaṭ lil-Ṭabarānī',
    'B233 - al-Majmūʿ al-Thamīn fī Ḥukm Duʿāʾ Ghayr Rabb al-ʿĀlamīn',
    'B234 - al-Jāmiʿ li-Sīrat al-Imām Ibn Qayyim al-Jawzīyah Khilāl Sittat Qurūn',
    'B235 - al-Dhikr wa-al-Duʿāʾ wa-al-ʿIlāj bi-al-Ruqá min al-Kitāb wa-al-Sunnah - taḥqīq Yāsir Fatḥī',
    'B236 - al-Tamhīd - Ibn ʿAbd al-Barr - taḥqīq Bashshār',
    'B237 - ʿAḏābāt al-ʿIlm',
    'B238 - Fatḥ al-Karīm al-Laṭīf fī Sharḥ Bākūrat al-Taʿrīf bi-al-Muhimm min al-Taṣrīf',
    'B239 - Thalāthat al-Uṣūl wa-Shurūṭ al-Ṣalāh wa-al-Qawāʿid al-Arbaʿ',
    'B240 - al-Shāmil fī al-Ṣināʿah al-Ṭibbīyah',
    'B241 - Fawāʾid al-Mustakhrajāt min Khilāl Musnad Abī ʿAwānah',
    'B242 - Istikhrāj al-Jidāl min al-Qurʾān al-Karīm',
    'B243 - al-Laṭāʾif',
    'B244 - Birr al-Wālidayn - Ibn al-Jawzī',
    'B245 - Majallat al-Tankīt wa-al-Tabkīt',
    'B246 - Madhhab Jumhūr al-Ashāʿirah fī al-Qurʾān',
    'B247 - Taḥqīq al-Āyāt al-Bayyināt fī ʿAdam Samāʿ al-Amwāt',
    'B248 - Ḥaqīqat al-Sunnah wa-al-Bidʿah = al-Amr bi-al-Ittibāʿ wa-al-Nahy ʿan al-Ibtidāʿ',
    'B249 - al-Daʿwah wa-al-Duʿāh min Ẓilāl Āyah',
    'B250 - al-Dhukhr al-Ḥarīr bi-Sharḥ Mukhtaṣar al-Taḥrīr',
    'B251 - Ṭarīq al-Hijratayn wa-Bāb al-Saʿādatayn [ʿAṭāʾāt al-ʿIlm]',
    'B252 - ʿUddat al-Ṣābirīn wa-Dhakhīrat al-Shākirīn [ʿAṭāʾāt al-ʿIlm]',
    'B253 - al-Ṣalāh - Ibn al-Qayyim [ʿAṭāʾāt al-ʿIlm]',
    'B254 - Dalīl al-Ṭālibīn li-Kalām al-Naḥwīyīn',
    'B255 - al-Maqāṣid al-Qurʾānīyah fī Sūrat «Qāf»',
    'B256 - Umm al-Muʾminīn Juwayrīyah bint al-Ḥārith',
    'B257 - Rafʿ al-Yadayn fī al-Ṣalāh',
    'B258 - al-Naṣīḥah al-Kāfiyah li-man Khaṣṣahu Allāh bi-al-ʿĀfiyah',
    'B259 - Kashf al-Ẓunūn ʿan Asāmī al-Kutub wa-al-Funūn [al-Furqān]',
    'B260 - Irshād al-Faqīh ilá Maʿrifat Adillat al-Tanbīh',
    'B261 - Faḍl al-Raḥīm al-Wadūd Takhrīj Sunan Abī Dāwūd',
    'B262 - al-Ṭahūr - Abū ʿUbayd - taḥqīq Mashhūr',
    'B263 - al-Zuhd li-Asad ibn Mūsá',
    'B264 - Taḥqīq al-Īmān li-Ibn Taymīyah',
    'B265 - Marwīyāt Faḍāʾil ʿAlī ibn Abī Ṭālib fī al-Mustadrak',
    'B266 - Ādāb al-Baḥth wa-al-Munāẓarah',
    'B267 - al-Iqnāʿ fī Ḥujjīyat al-Ijmāʿ',
    'B269 - Ghurar al-Bayān min Sūrat Yūsuf -ʿalayhi al-salām- fī al-Qurʾān',
    'B270 - Idāmat al-Naẓar fī Taḥrīr Nukhbat al-Fikar',
    'B271 - al-Intiṣār fī Ḥujjīyat Qawl al-Ṣaḥābah al-Akhyār',
    'B272 - al-Ḥukm min al-Muʿāmalāt wa-al-Mawārīth wa-al-Nikāḥ wa-al-Aṭʿimah fī Āyāt al-Qurʾān al-Karīm',
    'B273 - Tatimmat Ṣiwān al-Ḥikmah',
    'B274 - al-Maḥṣūl fī Sharḥ Ṣafwat al-Uṣūl',
    'B275 - Dafʿ Daʿwá al-Muʿāriḍ al-ʿAqlī ʿan al-Aḥādīth al-Mutaʿalliqah bi-Masāʾil al-Iʿtiqād',
    'B276 - al-Ḥāfiẓ Ibn al-Jārūd wa-Kitābuhu al-Muntaqá',
    'B277 - Aṭwāq al-Dhahab fī al-Mawāʿiẓ wa-al-Khuṭab = Kitāb al-Maqālāt',
    'B278 - al-Muntaqá - Ibn al-Jārūd - Qism min Awwalihi',
    'B279 - Itḥāf al-Arīb bi-Sharḥ al-Ghāyah wa-al-Taqrīb',
    'B280 - al-Bayt al-Saʿīd wa-Khilāf al-Zawjayn',
    'B281 - Dafʿ Īhām al-Iḍṭirāb ʿan Āyāt al-Kitāb [ʿAṭāʾāt al-ʿIlm]',
    'B282 - Mudhakkirat Uṣūl al-Fiqh ʿalá Rawḍat al-Nāẓir [ʿAṭāʾāt al-ʿIlm]',
    'B283 - Nathr al-Wurūd Sharḥ Marāqī al-Suʿūd',
    'B284 - Muḥāḍarāt al-Shanqīṭī',
    'B285 - al-Madākhil ilá Āthār Shaykh al-Islām Ibn Taymīyah',
    'B287 - al-Fatāwá - Muḥammad al-Amīn al-Shanqīṭī',
    'B288 - al-Taʿlīq wa-al-Īḍāḥ ʿalá Tafsīr al-Jalālayn - Juzʾ 1',
    'B291 - Jawāb al-Iʿtirāḍāt al-Miṣrīyah ʿalá al-Fatwá al-Ḥamawīyah',
    'B292 - Riḥlat al-Ḥajj ilá Bayt Allāh al-Ḥarām',
    'B293 - al-Durūs al-Muhimmah li-ʿĀmmat al-Ummah',
    'B294 - Shifāʾ al-ʿAlīl fī Ikhtiṣār Ibṭāl al-Taḥlīl',
    'B295 - Akhbār al-Naḥwīyīn - Abū Ṭāhir ibn Abī Hāshim - taḥqīq Majdī al-Sayyid',
    'B296 - Mukhtaṣar al-Ṣārim al-Maslūl ʿalá Shātim al-Rasūl',
    'B297 - al-Ajwibah al-ʿĪthāwīyah ʿan al-Masāʾil al-Ṭarābulusīyah',
    'B298 - Sulāfat al-ʿAṣr fī Maḥāsin al-Shuʿarāʾ bi-Kull Miṣr',
    'B299 - Risālah fī al-Wuḍūʾ wa-al-Ghusl wa-al-Ṣalāh',
    'B8207 - al-Amr bi-al-Maʿrūf wa-al-Nahy ʿan al-Munkar - Ibn Abī al-Dunyā',
    'B8208 - al-Bidaʿ wa-al-Nahy ʿanhā',
    'B8209 - al-Targhīb fī Faḍāʾil al-Aʿmāl wa-Thawāb dhālika li-Ibn Shāhīn',
    'B8210 - al-Tawḥīd li-Ibn Mandah - taḥqīq al-Faqīhī',
    'B8212 - al-Jumʿah wa-Faḍluhā li-Aḥmad ibn ʿAlī al-Marwazī',
    'B8213 - al-Ḥathth ʿalá al-Tijārah - min «al-Jāmiʿ» lil-Khallāl - taḥqīq al-Ḥaddād',
    'B8215 - al-Zuhd li-Abī Dāwūd',
    'B8216 - al-Zuhd li-Ibn Abī al-Dunyā',
    'B8217 - Tarājuʿāt al-Albānī',
    'B8218 - al-Qirāʾah khalf al-Imām lil-Bukhārī',
    'B8219 - al-Qaḍāʾ li-Surayj ibn Yūnus',
    'B8220 - al-Yaqīn li-Ibn Abī al-Dunyā',
    'B8221 - Tathbīt al-Imāmah wa-Tartīb al-Khilāfah li-Abī Nuʿaym al-Aṣbahānī',
    'B8222 - Taḥrīm al-Nard wa-al-Shiṭranj wa-al-Malāhī lil-Ājurrī',
    'B8223 - Takhrīj al-Aḥādīth al-Marfūʿah al-Musnadah fī Kitāb al-Tārīkh al-Kabīr',
    'B8224 - Tasmiyat mā Intahá Ilaynā min al-Ruwāh ʿan Saʿīd ibn Manṣūr li-Abī Nuʿaym',
    'B8225 - Juzʾ fīhi Majlisān min Imlāʾ al-Nasāʾī',
    'B8226 - Juzʾ min Ḥadīth Ibn Shāhīn',
    'B8227 - Ḥadīth Abī al-Faḍl al-Zuhrī',
    'B8228 - Dhamm al-Baghy li-Ibn Abī al-Dunyā',
    'B8229 - Maʿānī al-Qirāʾāt lil-Azharī',
    'B8230 - Dhamm al-Malāhī li-Ibn Abī al-Dunyā',
    'B8232 - Ruʾyat Allāh li-Ibn al-Naḥḥās',
    'B8233 - Sabʿat Majālis min Amālī Abī Ṭāhir al-Mukhalliṣ',
    'B8234 - Ṣifat al-Jannah li-Ibn Abī al-Dunyā - taḥqīq Salīm',
    'B8235 - Ṣifat al-Nifāq wa-Dhamm al-Munāfiqīn lil-Firyābī',
    'B8236 - Gharāʾib Mālik ibn Anas li-Ibn al-Muẓaffar',
    'B8237 - Faḍāʾil al-Khulafāʾ al-Rāshidīn li-Abī Nuʿaym al-Aṣbahānī',
    'B8238 - Faḍāʾil al-Ṣaḥābah lil-Dāraquṭnī',
    'B8239 - Faḍl al-Ramy wa-Taʿlīmihi lil-Ṭabarānī',
    'B8240 - Fawāʾid Abī Yaʿlá al-Khalīlī',
    'B8241 - Dhamm al-Ghībah wa-al-Namīmah li-Ibn Abī al-Dunyā',
    'B8242 - Kalām al-Layālī wa-al-Ayyām li-Ibn Abī al-Dunyā',
    'B8243 - Masāwiʾ al-Akhlāq lil-Kharāʾiṭī',
    'B8244 - Muʿjam Ibn al-Muqriʾ',
    'B8245 - Adab al-Nufūs lil-Ājurrī',
    'B8246 - al-Arbaʿūn ʿalá Madhhab al-Mutaḥaqqiqīn min al-Ṣūfīyah li-Abī Nuʿaym al-Aṣbahānī',
    'B8247 - al-Arbaʿūn fī Shuyūkh al-Ṣūfīyah lil-Mālīnī',
    'B8248 - al-Amr bi-al-Maʿrūf wa-al-Nahy ʿan al-Munkar - min «al-Jāmiʿ» lil-Khallāl',
    'B8249 - Tārīkh Dārayyā - ʿAbd al-Jabbār al-Khawlānī',
    'B8251 - al-Baʿth li-Ibn Abī Dāwūd',
    'B8252 - al-Baytūtah',
    'B8253 - al-Tawbah li-Ibn Abī al-Dunyā',
    'B8254 - al-Tawakkul ʿalá Allāh li-Ibn Abī al-Dunyā',
    'B8255 - al-Duʿāʾ - al-Muḥāmalī',
    'B8256 - al-Riqqah wa-al-Bukāʾ li-Ibn Abī al-Dunyā',
    'B8257 - Ibṭāl al-Ḥiyal li-Ibn Baṭṭah',
    'B8258 - Ithbāt ʿAdhāb al-Qabr lil-Bayhaqī',
    'B8259 - al-Ṣabr wa-al-Thawāb ʿalayhi li-Ibn Abī al-Dunyā',
    'B8266 - al-ʿUqūbāt li-Ibn Abī al-Dunyā',
    'B8267 - al-Fawāʾid al-Muntaqāh al-ʿAwālī al-Ḥisān lil-Samarqandī',
    'B8268 - al-Fawāʾid li-Abī al-Shaykh al-Aṣbahānī',
    'B8269 - al-Qubal wa-al-Muʿānaqah wa-al-Muṣāfaḥah li-Ibn al-Aʿrābī',
    'B8271 - al-Qirāʾah ʿinda al-Qubūr - min «al-Jāmiʿ» lil-Khallāl',
    'B8272 - Aḥādīth al-Shāmūkhī',
    'B8273 - al-Maṭar wa-al-Raʿd wa-al-Barq li-Ibn Abī al-Dunyā',
    'B8274 - al-Muntaqá min Kitāb al-Ṭabaqāt li-Abī ʿUrūbah al-Ḥarrānī',
    'B8275 - Thalāthat Majālis min Amālī Ibn Mardawayh',
    'B8276 - Aḥkām al-ʿĪdayn lil-Firyābī',
    'B8279 - Siḥr al-Balāghah wa-Sirr al-Barāʿah',
    'B8301 - Rasāʾil falsafīyah li-Ibn Bājjah',
    'B8305 - Marzubān-nāmah',
    'B8312 - Lamasāt bayānīyah fī nuṣūṣ min al-tanzīl - muḥāḍarāt',
    'B8313 - Azamāt al-shabāb asbāb wa-ḥulūl',
    'B8314 - al-ʿAwāṣim min al-Qawāṣim [Dār al-Jīl]',
    'B8316 - al-Nukat ʿalá Kitāb Ibn al-Ṣalāḥ li-Ibn Ḥajar',
    'B8317 - Maṣraʿ al-Taṣawwuf = Tanbīh al-Ghabī ilá Takfīr Ibn ʿArabī wa-Taḥdhīr al-ʿIbād min Ahl al-ʿInād bi-Bidʿat al-Ittiḥād',
    'B8320 - Tafsīr al-Samʿānī',
    'B8322 - Majallat al-Buḥūth al-Islāmīyah',
    'B8323 - Ghiyāth al-Umam fī Iltiyāth al-Ẓulam',
    'B8338 - al-Thālith wa-al-Thamānūn min al-Fawāʾid al-Afrād',
    'B8340 - al-Ghidhāʾ wa-al-Taghdhiyah',
    'B8343 - Naẓarīyat al-Maqāṣid ʿinda al-Imām al-Shāṭibī',
    'B8345 - Siyāsat-nāmah = Siyar al-Mulūk',
    'B8346 - Tafsīr al-Māwardī = al-Nukat wa-al-ʿUyūn',
    'B8349 - Maʿrifat al-Qurrāʾ al-Kibār ʿalá al-Ṭabaqāt wa-al-Aʿṣār',
    'B8350 - Kitābat al-Baḥth al-ʿIlmī ṣiyāghah jadīdah',
    'B8352 - Sharḥ al-ʿAqīdah al-Ṭaḥāwīyah [al-Risālah]',
    'B8353 - Lawāmiʿ al-Anwār al-Bahīyah',
    'B8354 - Tanshiʾat al-ṭifl wa-subul al-wālidayn fī muʿāmalatihi wa-muwājahat mushkilātihi',
    'B8356 - Majallat Majmaʿ al-Fiqh al-Islāmī',
    'B8360 - Mishkāt al-Maṣābīḥ',
    'B8361 - al-Sunan al-Kubrá - al-Nasāʾī [al-Risālah]',
    'B8362 - Shifāʾ al-Gharām bi-Akhbār al-Balad al-Ḥarām',
    'B8363 - Mukhtaṣar al-Ṣawāʿiq al-Mursalah ʿalá al-Jahmīyah wa-al-Muʿaṭṭilah',
    'B8367 - Ahdāf al-Tarbiyah al-Islāmīyah',
    'B8368 - al-Baḥth al-ʿIlmī: asāsīyātuhu al-naẓarīyah wa-mumārasatuhu al-ʿamalīyah',
    'B8370 - Madārij al-Sālikīn [al-Kitāb al-ʿArabī]',
    'B8372 - Ṣayd al-Afkār fī al-Adab wa-al-Akhlāq wa-al-Ḥikam wa-al-Amthāl',
    'B8376 - al-Bidāyah wa-al-Nihāyah - taḥqīq Shīrī',
    'B8378 - Anmūdhaj jalīl fī asʾilah wa-ajwibah ʿan gharāʾib āy al-tanzīl',
    'B8379 - al-Wajīz fī Īḍāḥ Qawāʿid al-Fiqh al-Kullīyah',
    'B8380 - Fatāwá Nūr ʿalá al-Darb li-Ibn Bāz - bi-ʿināyat al-Ṭayyār wa-al-Mūsá - qism al-ʿaqīdah',
    'B8381 - Fatāwá al-Lajnah al-Dāʾimah - al-Majmūʿah al-Ūlá',
    'B8382 - al-Ṭarīq ilá al-Islām',
    'B8383 - al-Ṭahārah (maṭbūʿ ḍimna Muʾallafāt al-Shaykh Muḥammad ibn ʿAbd al-Wahhāb, al-Juzʾ al-Thālith)',
    'B8384 - al-ʿArab fī al-ʿUṣūr al-Qadīmah',
    'B8459 - al-Mughrib fī Tartīb al-Muʿrib [al-Kitāb al-ʿArabī]',
    'B8460 - Maʾāthir al-Ināfah fī Maʿālim al-Khilāfah',
    'B8463 - al-Mughnī li-Ibn Qudāmah [Maktabat al-Qāhirah]',
    'B8466 - Ibrāz al-Ḥikam min Ḥadīth Rafʿ al-Qalam',
    'B8473 - Tafsīr Ibn Kathīr - taḥqīq al-Salāmah',
    'B8474 - Aḥādīth Ayyūb al-Sakhtiyānī',
    'B8476 - Fatāwá wa-Rasāʾil Samāḥat al-Shaykh Muḥammad ibn Ibrāhīm ibn ʿAbd al-Laṭīf Āl al-Shaykh',
    'B8477 - al-Tārīkh al-Kabīr li-Ibn Abī Khaythamah - al-Sifr al-Thālith [al-Fārūq]',
    'B8487 - al-Tahdhīb fī Ikhtiṣār al-Mudawwanah',
    'B8488 - al-Jumūʿ al-Bahīyah lil-ʿAqīdah al-Salafīyah',
    'B8490 - al-Ijābah li-Īrād mā Istadrakathu ʿĀʾishah ʿalá al-Ṣaḥābah - taḥqīq Rifʿat Fawzī',
    'B8491 - al-Nāsikh wa-al-Mansūkh - Qatādah',
    'B8493 - Musnad al-Ḥumaydī',
    'B8494 - al-Zuhd li-Aḥmad ibn Ḥanbal',
    'B8496 - al-Ḥisbah - Jāmiʿat al-Madīnah',
    'B8497 - Fann al-Maqālah',
    'B8501 - al-Adab wa-Funūnuh - dirāsah wa-naqd',
    'B8502 - Majallat al-Aḥkām al-ʿAdlīyah',
    'B8505 - al-Kāmil fī al-Lughah wa-al-Adab',
    'B8506 - Iʿjāz al-Qurʾān wa-al-Balāghah al-Nabawīyah lil-Rāfiʿī',
    'B8514 - al-ʿAqd al-Thamīn fī Sharḥ Aḥādīth Uṣūl al-Dīn',
    'B8515 - al-ʿInāyah bi-al-Qurʾān al-Karīm fī al-ʿAhd al-Nabawī al-Sharīf',
    'B8517 - al-ʿInāyah bi-al-Qurʾān al-Karīm wa-ʿUlūmihi min Bidāyat al-Qarn al-Rābiʿ al-Hijrī ilá ʿAṣrinā al-Ḥāḍir',
    'B8518 - al-ʿAyn wa-al-Athar fī ʿAqāʾid Ahl al-Athar',
    'B8519 - al-Ghārah al-Tabshīrīyah ʿalá Aṣālat al-Qurʾān al-Karīm',
    'B8520 - al-ʿUyūb al-Manhajīyah fī Kitābāt al-Mustashriq Shākht al-Mutaʿalliqah bi-al-Sunnah al-Nabawīyah',
    'B8522 - Alfīyat Ibn Mālik [al-Taʿāwun]',
    'B8523 - al-Qaṭʿīyah min al-Adillah al-Arbaʿah',
    'B8524 - al-Qawāʿid al-Arbaʿ (maṭbūʿ ḍimna Muʾallafāt al-Shaykh Muḥammad ibn ʿAbd al-Wahhāb, al-Juzʾ al-Awwal)',
    'B8526 - al-Qawāʿid wa-al-Fawāʾid al-Uṣūlīyah wa-mā yatbaʿuhā min al-Aḥkām al-Farʿīyah',
    'B8527 - al-Qawl al-Sadīd fī al-Radd ʿalá man Ankira Taqsīm al-Tawḥīd',
    'B8528 - Ḥayāt al-Ṣaḥābah',
    'B8529 - al-Qawl al-Sadīd sharḥ Kitāb al-Tawḥīd [al-Nafāʾis]',
    'B8530 - al-Qawl al-Mubīn fī Sīrat Sayyid al-Mursalīn',
    'B8531 - al-Kabāʾir li-Muḥammad ibn ʿAbd al-Wahhāb (maṭbūʿ ḍimna Muʾallafāt al-Shaykh Muḥammad ibn ʿAbd al-Wahhāb, al-Juzʾ al-Awwal)',
    'B8532 - al-Kalimāt al-Nāfiʿah fī al-Mukaffirāt al-Wāqiʿah',
    'B8533 - al-Kanz al-Lughawī fī al-Lisān al-ʿArabī',
    'B8534 - al-Lubāb fī al-Fiqh al-Shāfiʿī',
    'B8536 - al-Lumaʿ fī Uṣūl al-Fiqh lil-Shīrāzī',
    'B8537 - al-Muʾallafāt fī al-Ḥadīth wa-ʿUlūmihi fī al-ʿAhd al-Jumhūrī fī Turkiyā - bibliyūghrāfiyā',
    'B8538 - al-Mujtamaʿ wa-al-Usrah fī al-Islām',
    'B8540 - Sharḥ Sunan Abī Dāwūd lil-ʿAynī',
    'B8541 - al-Muḥāḍarah al-Difāʿīyah ʿan al-Sunnah al-Muḥammadīyah',
    'B8542 - al-Mukhtalaf fīhim',
    'B8543 - al-Mudāyanah',
    'B8544 - Sharḥ Sunan Ibn Mājah li-Mughlaṭāy - taḥqīq ʿUwayḍah',
    'B8546 - al-Madīnah al-Munawwarah al-Nabawīyah: faḍluhā, faḍl sākinihā, ziyāratuhā',
    'B8548 - al-Marʾah fī Ḥayāt Imām al-Daʿwah al-Shaykh Muḥammad ibn ʿAbd al-Wahhāb (maṭbūʿ ḍimna Buḥūth Nadwat Daʿwat al-Shaykh Muḥammad ibn ʿAbd al-Wahhāb, al-Juzʾ al-Awwal)',
    'B8549 - Faṣl al-Khiṭāb fī Sharḥ Masāʾil al-Jāhilīyah - taḥqīq Yūsuf al-Saʿīd',
    'B8550 - al-Masāʾil al-Muhimmah fīmā Yaḥtāj ilayhi al-ʿĀqid ʿinda al-Khuṭūb al-Mudlahimmah',
    'B8552 - al-Maṣāḥif al-Makhṭūṭah fī al-Qarn al-Ḥādī ʿAshar al-Hijrī',
    'B8553 - al-Muṣāraḥah fī Aḥkām al-Muṣāfaḥah',
    'B8554 - al-Muṣaffā bi-Akuff Ahl al-Rusūkh min ʿIlm al-Nāsikh wa-al-Mansūkh',
    'B8555 - al-Maṭlab al-Ḥamīd fī Bayān Maqāṣid al-Tawḥīd',
    'B8556 - al-Muṭlaq wa-al-Muqayyad',
    'B8558 - al-Maʿājim al-Mufahrasah li-Alfāẓ al-Qurʾān al-Karīm',
    'B8559 - al-Muʿjib fī Talkhīṣ Akhbār al-Maghrib',
    'B8560 - al-Muʿjam al-Mawsūʿī li-Alfāẓ al-Qurʾān al-Karīm wa-Qirāʾātihi',
    'B8561 - Maqāmāt ʿAbd al-Raḥmān ibn Ḥasan',
    'B8562 - al-Muqtarab fī Bayān al-Muḍṭarib',
    'B8563 - al-Muqawwimāt al-Shakhṣīyah li-Muʿallim al-Qurʾān al-Karīm',
    'B8564 - al-Maktabah al-Islāmīyah',
    'B8565 - Iʿānat al-Mustafīd bi-Sharḥ Kitāb al-Tawḥīd',
    'B8566 - al-Manār al-Munīf fī al-Ṣaḥīḥ wa-al-Ḍaʿīf - taḥqīq Abī Ghuddah',
    'B8567 - al-Manẓūmah al-Bayqūnīyah',
    'B8569 - al-Muqaddamāt fī al-Jughrāfiyā al-Ṭabīʿīyah',
    'B8570 - al-Mūjaz fī Qawāʿid al-Lughah al-ʿArabīyah',
    'B8571 - al-Mawrid al-ʿAdhb al-Zulāl fī Kashf Shubah Ahl al-Ḍalāl (maṭbūʿ ḍimna al-Rasāʾil wa-al-Masāʾil al-Najdīyah, al-Juzʾ al-Rābiʿ, al-Qism al-Awwal)',
    'B8572 - al-Mawsūʿah al-Ḥadīthīyah al-Shāmilah bayna al-Wāqiʿ wa-al-Maʾmūl',
    'B8573 - Ittiḥāf al-Jamāʿah bimā Jāʾa fī al-Fitan wa-al-Malāḥim wa-Ashrāṭ al-Sāʿah',
    'B8574 - al-Mawsūʿah al-Ḥadīthīyah bayna al-Wāqiʿ wa-al-Maʾmūl',
    'B8575 - al-Taṣrīḥ bimā Tawātara fī Nuzūl al-Masīḥ',
    'B8578 - al-Najāh al-Najāh yā ʿIbād Allāh',
    'B8585 - al-Tuḥfah al-Madanīyah fī al-ʿAqīdah al-Salafīyah',
    'B8586 - al-Taʿlīqāt ʿalá Matn Lumʿat al-Iʿtiqād li-Ibn Jibrīn',
    'B8588 - al-Tawḥīd wa-Bayān al-ʿAqīdah al-Salafīyah al-Naqīyah',
    'B8589 - al-Tawḍīḥ wa-al-Bayān li-Shajarat al-Īmān',
    'B8590 - al-Ḥawādith wa-al-Bidaʿ',
    'B8594 - Juhūd ʿUlamāʾ al-Ḥanafīyah fī Ibṭāl ʿAqāʾid al-Qubūrīyah',
    'B8596 - al-Nuṣayrīyah: ṭughāt Sūriyā aw al-ʿAlawīyūn kamā sammāhum al-Faransīyūn',
    'B8599 - Risālah fī Ḥukm al-Siḥr wa-al-Kihānah maʿa baʿḍ al-Fatāwá al-Muhimmah',
    'B8600 - Sharḥ Thalāthat al-Uṣūl li-Ṣāliḥ al-Fawzān',
    'B8601 - Sharḥ al-Sunnah lil-Barbahārī',
    'B8602 - al-Naqd al-Ṣaḥīḥ limā Uʿturiḍa min Aḥādīth al-Maṣābīḥ',
    'B8605 - Sharḥ ʿAqīdat al-Imām al-Mujaddid Muḥammad ibn ʿAbd al-Wahhāb',
    'B8608 - Qawāʿid al-Aḥkām fī Maṣāliḥ al-Anām',
    'B8609 - Taqrīb al-Tahdhīb',
    'B8610 - ʿAqīdat al-Tawḥīd wa-Bayān mā Yuḍāddihā min al-Shirk al-Akbar wa-al-Aṣghar wa-al-Taʿṭīl wa-al-Bidaʿ wa-Ghayr dhālika',
    'B8612 - Majmūʿ Fatāwá Faḍīlat al-Shaykh Ṣāliḥ ibn Fawzān',
    'B8613 - Fatāwá wa-Rasāʾil al-Shaykh ʿAbd al-Razzāq ʿAfīfī',
    'B8615 - al-Fikrah al-Sunnīyah wa-al-Ḥājah Ilayhā',
    'B8618 - al-Taḥjīl fī Takhrīj mā lam Yukharraj min al-Aḥādīth wa-al-Āthār fī Irwāʾ al-Ghalīl',
    'B8620 - Akhbār al-Zamān',
    'B8622 - al-Ṣārim al-Munkī fī al-Radd ʿalá al-Subkī',
    'B8623 - Miʾat ḥadīth sāqiṭah min Sunan al-Nasāʾī al-Kubrá al-Maṭbūʿ',
    'B8624 - al-Nikāḥ wa-al-Ṭalāq aw al-Zawāj wa-al-Firāq',
    'B8630 - Naqd Marātib al-Ijmāʿ',
    'B8631 - Aḥkām al-Aḥwāl al-Shakhṣīyah fī al-Sharīʿah al-Islāmīyah',
    'B8632 - al-Ḍuʿafāʾ al-Ṣaghīr lil-Bukhārī - taḥqīq Abī al-ʿAynayn',
    'B8633 - Madkhal fī ʿUlūm al-Qirāʾāt',
    'B8634 - al-Ashbāh wa-al-Naẓāʾir - al-Subkī',
    'B8635 - al-Fatḥ al-Samāwī',
    'B8636 - Takhrīj Aḥādīth al-Kashshāf',
    'B8637 - Dhayl al-Qawl al-Musaddad',
    'B8638 - Fiqh al-Usrah',
    'B8639 - Ṣafaḥāt fī ʿUlūm al-Qirāʾāt',
    'B8640 - Fiqh al-Nikāḥ wa-al-Farāʾiḍ',
    'B8641 - Taṭawwur al-Adab al-Ḥadīth fī Miṣr',
    'B8642 - al-Waḥy al-Muḥammadī',
    'B8643 - al-Waqf al-Qurʾānī wa-Atharuhu fī al-Tarjīḥ ʿinda al-Ḥanafīyah',
    'B8644 - Nuzūl al-Qurʾān ʿalá Sabʿat Aḥruf',
    'B8645 - Bayna al-ʿAqīdah wa-al-Qiyādah',
    'B8646 - Tārīkh al-Falsafah al-Ḥadīthah',
    'B8647 - al-ʿAqāʾid al-Islāmīyah',
    'B8648 - Fatāwī al-Khalīlī ʿalá al-Madhhab al-Shāfiʿī',
    'B8649 - al-Farāʾid al-Ḥisān fī ʿAdd Āy al-Qurʾān',
    'B8650 - al-Hādī sharḥ Ṭayyibat al-Nashr fī al-Qirāʾāt al-ʿAshr',
    'B8651 - Fann al-Kitābah al-Ṣuḥufīyah',
    'B8653 - al-Mughnī fī Taṣrīf al-Afʿāl',
    'B8656 - al-Ḥadīth wa-al-Muḥaddithūn',
    'B8657 - al-Riyāḍ al-Naḍirah fī Manāqib al-ʿAsharah',
    'B8658 - Tafsīr Ibn Abī Ḥātim',
    'B8660 - al-Muḥtasab fī Tabyīn Wujūh Shawādhdh al-Qirāʾāt wa-al-Īḍāḥ ʿanhā [al-Majlis al-Aʿlá]',
    'B8661 - Kayfa taktubu baḥthan aw risālah: dirāsah manhajīyah li-kitābat al-buḥūth wa-iʿdād rasāʾil al-mājistīr wa-al-duktūrāh',
    'B8663 - al-Tawḍīḥ al-Abhar li-Tadhkirat Ibn al-Mulaqqin fī ʿIlm al-Athar',
    'B8665 - Dustūr al-Akhlāq fī al-Qurʾān',
    'B8666 - al-Fann wa-Madhāhibuhu fī al-Shiʿr al-ʿArabī',
    'B8667 - al-Mumtiʿ al-Kabīr fī al-Taṣrīf',
    'B8668 - Maʿālim Ḥaḍārāt al-Sharq al-Adná al-Qadīm',
    'B8669 - Aḍwāʾ ʿalá al-Thaqāfah al-Islāmīyah',
    'B8670 - al-Baḥth al-Lughawī ʿinda al-ʿArab',
    'B8671 - al-Isrāʾīlīyāt wa-al-Mawḍūʿāt fī Kutub al-Tafsīr',
    'B8672 - al-Mufīd fī Muhimmāt al-Tawḥīd',
    'B8674 - Buḥūth fī Tārīkh al-Sunnah al-Musharrafah',
    'B8675 - Khizānat al-Adab wa-Ghāyat al-Arab li-Ibn Ḥijjah al-Ḥamawī',
    'B8676 - al-Ibānah ʿan Maʿānī al-Qirāʾāt',
    'B8677 - Munjid al-Muqriʾīn wa-Murshid al-Ṭālibīn',
    'B8678 - al-Siyāsah al-Sharʿīyah fī al-Shuʾūn al-Dustūrīyah wa-al-Khārijīyah wa-al-Mālīyah',
    'B8679 - Ittijāhāt al-Tafsīr fī al-Qarn al-Rābiʿ ʿAshar',
    'B8680 - Naqḍ al-Dārimī ʿalá al-Marīsī - taḥqīq al-Almaʿī',
    'B8681 - Taysīr Muṣṭalaḥ al-Ḥadīth',
    'B8682 - al-Ṭabaqāt - li-Khalīfah ibn Khayyāṭ - taḥqīq Zakkār',
    'B8697 - Iʿrāb lā ilāha illā Allāh',
    'B8707 - al-Ibdāl fī Lughāt al-Azd: dirāsah ṣawtīyah fī ḍawʾ ʿilm al-lughah al-ḥadīth',
    'B8709 - al-Āthār al-Tarbawīyah li-Dirāsat al-Lughah al-ʿArabīyah',
    'B8710 - al-Āthār al-Sayyiʾah lil-Waḍʿ fī al-Ḥadīth',
    'B8711 - al-Ijmāʿ fī al-Sharīʿah al-Islāmīyah',
    'B8712 - al-Athar al-Mashhūr ʿan al-Imām Mālik raḥimahu Allāh fī Ṣifat al-Istiwāʾ',
    'B8713 - al-Aḥādīth al-Arbaʿīn al-Nawawīyah maʿa mā Zāda ʿalayhā Ibn Rajab wa-ʿalayhā al-Sharḥ al-Mūjaz al-Mufīd',
    'B8725 - al-Adillah wa-al-Barāhīn ʿalá Ḥurmat al-Tadkhīn',
    'B8727 - al-Istishrāq wa-Juhūduhu wa-Ahdāfuhu fī Muḥārabat al-Islām wa-al-Tashwīsh ʿalá Daʿwatihi',
    'B8729 - al-Asfār al-Muqaddasah ʿinda al-Yahūd wa-Atharuhā fī Inḥirāfihim: ʿArḍ wa-Naqd',
    'B8734 - al-Islām fī Afrīqiyā ʿabra al-Tārīkh',
    'B8735 - al-Islām fī Sīriyālīyūn',
    'B8736 - al-Islām wa-al-Ḥarakāt al-Haddāmah al-Muʿāṣirah',
    'B8746 - al-Islām wa-al-Madhāhib al-Ishtirākīyah',
    'B8753 - Manhaj wa-Dirāsāt li-Āyāt al-Asmāʾ wa-al-Ṣifāt - Majallat al-Jāmiʿah al-Islāmīyah',
    'B8754 - al-Isnād ʿinda ʿUlamāʾ al-Qirāʾāt',
    'B8762 - al-Iʿlām wa-al-Daʿwah ilá Allāh',
    'B8766 - al-Ilḥād wa-al-Ẓulm fī al-Masjid al-Ḥarām bayna al-Irādah wa-al-Tanfīdh',
    'B8771 - al-Imām Abū al-ʿAbbās Ibn Surayj al-Mutawaffá sanah 306 H وآrāʾuhu al-Uṣūlīyah',
    'B8772 - al-Imām al-Bukhārī wa-Kitābuhu al-Jāmiʿ al-Ṣaḥīḥ',
    'B8775 - al-Imām Muslim wa-Ṣaḥīḥuhu',
    'B8776 - al-Imdād bi-Aḥkām al-Ḥidād',
    'B8783 - al-Anwār al-Raḥmānīyah li-Hidāyat al-Firqah al-Tījānīyah',
    'B8788 - al-Bidaʿ wa-Āthāruhā al-Sayyiʾah',
    'B8791 - al-Bidʿah Ḍawābiṭuhā wa-Atharuhā al-Sayyiʾ fī al-Ummah',
    'B8792 - al-Badīhīyāt fī al-Qurʾān al-Karīm',
    'B8793 - al-Badīʿ ʿinda al-Ḥarīrī',
    'B8795 - al-Barakah fī al-Rizq wa-al-Asbāb al-Jālibah lahā fī Ḍawʾ al-Kitāb wa-al-Sunnah',
    'B8797 - al-Bahāʾīyah iḥdá maṭāyā al-Istiʿmār wa-al-Ṣahyūnīyah',
    'B8801 - al-Tārīkh ʿinda Ibn Abī Shaybah',
    'B8802 - al-Taʾmīn ʿaqib al-Fātiḥah fī al-Ṣalāh',
    'B8810 - al-ʿIbādāt fī al-Islām wa-Atharuhā fī Iṣlāḥ al-Mujtamaʿ',
    'B8811 - al-ʿIbādāt fī al-Islām wa-Atharuhā fī Taḍāmun al-Muslimīn',
    'B8814 - al-ʿIbrah fī Shahr al-Ṣawm',
    'B8819 - al-ʿAql wa-al-Naql ʿinda Ibn Rushd',
    'B8820 - al-ʿAqīdah al-Ṣaḥīḥah wa-mā Yuḍāddihā',
    'B8823 - al-ʿAlmānīyah wa-Mawqif al-Islām minhā',
    'B8826 - al-Shāʾ',
    'B8827 - al-Arbaʿūn al-Mukhtārah min Ḥadīth al-Imām Abī Ḥanīfah',
    'B8829 - al-Ghazw al-Fikrī wa-Wasāʾiluhu',
    'B8831 - al-Ghazw al-Fikrī',
    'B8851 - al-Fatḥ al-ʿUmarī lil-Quds namūdhaj lil-daʿwah bi-al-ʿamal wa-al-qudwah',
    'B8855 - al-Qawl al-Mubīn fī Akhṭāʾ al-Muṣallīn',
    'B8856 - Ilqāʾ al-Ḍawʾ al-Qurʾānī ʿalá Kitābat al-Duktūr ʿAlawī ḥawla al-Nabhānī',
    'B8858 - al-Qāḍī ʿIyāḍ wa-Mafhūmuhu lil-Iʿjāz al-Qurʾānī',
    'B8862 - Mirʿāt al-Mafātīḥ sharḥ Mishkāt al-Maṣābīḥ',
    'B8871 - al-Qurʾān yataḥaddá',
    'B8874 - al-Qawāʿid al-Muthlá fī Ṣifāt Allāh wa-Asmāʾihi al-Ḥusná',
    'B8875 - al-Qawl al-Faṣl fī al-ʿAmal bi-al-Ḥadīth al-Mursal',
    'B8880 - al-Dāris fī Tārīkh al-Madāris',
    'B8884 - Dhayl al-Taqyīd fī Ruwāt al-Sunan wa-al-Asānīd',
    'B8889 - al-Fatḥ al-Mubīn bi-Sharḥ al-Arbaʿīn',
    'B8891 - al-Kashf ʿan Ṣāḥib al-Basīṭ fī al-Naḥw',
    'B8903 - al-Muʾtamar al-ʿĀlamī li-Tawjīh al-Daʿwah wa-Iʿdād al-Duʿāh',
    'B8905 - al-Mabāḥith al-ʿAqadīyah al-Mutaʿalliqah bi-al-Kabāʾir wa-Murtakibihā fī al-Dunyā',
    'B8907 - al-Mukhaddarāt akhṭar muʿawwiqāt al-tanmiyah',
    'B8908 - al-Mudārāh wa-Atharuhā fī al-ʿAlāqāt al-ʿĀmmah bayna al-Nās',
    'B8909 - al-Mudabbaj wa-Riwāyat al-Aqrān',
    'B8926 - al-Mustashriqūn fī al-Mīzān',
    'B8930 - al-Muskirāt min al-Nāḥiyah al-Nafsīyah',
    'B8936 - al-Muskirāt wa-al-Mukhaddarāt',
    'B8937 - al-Maṣāliḥ al-Mursalah [al-Jāmiʿah al-Islāmīyah]',
    'B8938 - al-Maṣlaḥah al-Mursalah: muḥāwalah li-basṭihā wa-naẓrah fīhā',
    'B8945 - al-Muʿjizāt wa-al-Ghaybīyāt bayna Baṣāʾir al-Tanzīl wa-Dayājīr al-Inkār wa-al-Taʾwīl',
    'B8946 - al-Mafhūm al-Ṣaḥīḥ lil-Tawassul',
    'B8949 - al-Adab al-Muqāran - Jāmiʿat al-Madīnah (mājistīr)',
    'B8951 - al-Mamālīk al-Baḥrīyah wa-Qaḍāʾihim ʿalá al-Ṣalībīyīn fī al-Shām',
    'B8952 - al-Manṣūb ʿalá al-Taqrīb',
    'B8953 - al-Manṣūb ʿalá Nazʿ al-Khāfiḍ fī al-Qurʾān',
    'B8954 - Uṣūl al-Daʿwah wa-Ṭuruquhā 2 - Jāmiʿat al-Madīnah',
    'B8955 - al-Manhaj al-Ṣaḥīḥ wa-Atharuhu fī al-Daʿwah ilá Allāh Taʿálá',
    'B8957 - al-Manhaj bayna al-Māḍī wa-al-Ḥāḍir',
    'B8958 - al-Manhaj li-Murīd al-ʿUmrah wa-al-Ḥajj',
    'B8959 - al-Manhal al-Maʾhūl bi-al-Bināʾ lil-Majhūl li-Abī al-Khayr Muḥammad ibn Ẓahīrah: taḥqīq wa-dirāsah',
    'B8965 - al-Nushūz bayna al-Zawjayn',
    'B8966 - al-Nubuwwah: iṣṭifāʾ wa-qudwah',
    'B8967 - Ṣafwat al-Tafāsīr',
    'B8970 - al-Daʿawāt al-Kabīr',
    'B8972 - al-Naqd al-Adabī wa-Maqāyīsuhu khilāl ʿAhd al-Rasūl ṣallá Allāh ʿalayhi wa-sallam wa-ʿAṣr al-Khilāfah al-Rāshidah',
    'B8973 - al-Naqṣ min al-Naṣṣ: ḥaqīqatuhu wa-ḥukmuhu wa-athar dhālika fī al-iḥtijāj bi-al-Sunnah al-Āḥādīyah',
    'B8979 - al-Hijrah al-Nabawīyah - dirāsah wa-taḥlīl-',
    'B8983 - al-Wāsiṭah bayna al-Ḥaqq wa-al-Khalq',
    'B8987 - al-Waḥdah al-Islāmīyah',
    'B8989 - al-Waraqāt fīmā Yakhtalifu fīhi al-Rijāl wa-al-Nisāʾ',
    'B8990 - al-Waḥdah al-Islāmīyah: ususuhā wa-wasāʾil taḥqīqihā',
    'B8996 - Ilá alladhīna Yuḥāddūna Mafātiḥ al-Ghayb bi-ism al-ʿIlm al-Ḥadīth',
    'B9013 - Intishār al-Islām: al-Futūḥāt al-Islāmīyah zaman al-Rāshidīn',
    'B9015 - Inkār al-Jinn min Shaṭaḥāt al-Tafsīr al-Mawḍūʿī lil-Qurʾān',
    'B9026 - Ahammīyat al-Daʿwah',
    'B9027 - Ahammīyat Ṣalāt al-Istisqāʾ fī al-Islām wa-al-Istighāthah al-Mashrūʿah',
    'B9046 - Baḥth ʿAqadī fī Lafẓ al-Sayyid',
    'B9047 - Baḥth fī Ijābat al-Daʿwah',
    'B9051 - Juzʾ Aḥmad ibn ʿIṣām',
    'B9057 - al-Durr al-Maṣūn fī ʿUlūm al-Kitāb al-Maknūn',
    'B9059 - Tuḥfat al-Muḥtāj fī Sharḥ al-Minhāj wa-Ḥawāshī al-Sharwānī wa-al-ʿAbbādī',
    'B9060 - Sharḥ Musnad Abī Ḥanīfah',
    'B9061 - Naẓm al-ʿUqyān fī Aʿyān al-Aʿyān',
    'B9062 - Kashf al-Asrār ʿan Uṣūl Fakhr al-Islām al-Bazdawī',
    'B9063 - al-Kashf al-Mubdī',
    'B9065 - Nukat al-Qurʾān al-Dāllah ʿalá al-Bayān fī Anwāʿ al-ʿUlūm wa-al-Aḥkām',
    'B9066 - al-Nukat fī al-Qurʾān al-Karīm',
    'B9068 - Naṣāʾiḥ manhajīyah li-Ṭālib ʿIlm al-Sunnah al-Nabawīyah',
    'B9074 - al-Amr bi-al-Maʿrūf wa-al-Nahy ʿan al-Munkar - ʿAbd al-Ghanī al-Maqdisī',
    'B9075 - al-Radd ʿalá Ibn al-Qaṭṭān fī Kitābihi Bayān al-Wahm wa-al-Īhām',
    'B9076 - al-Muttafiq wa-al-Muftaraq',
    'B9077 - al-Qawāʿid al-Ḥisān li-Tafsīr al-Qurʾān',
    'B9078 - Muḥāḍarāt al-Udabāʾ wa-Muḥāwarāt al-Shuʿarāʾ wa-al-Bulaghāʾ',
    'B9080 - al-Hadiyyah al-Hādiyah ilá al-Ṭāʾifah al-Tijānīyah',
    'B9081 - Amthāl al-ʿArab [al-Hilāl]',
    'B9082 - ʿIlal al-Dāraquṭnī = al-ʿIlal al-Wāridah fī al-Aḥādīth al-Nabawīyah',
    'B9083 - Dalīl al-Ḥājj wa-al-Muʿtamir wa-Zāʾir Masjid al-Rasūl ṣallá Allāh ʿalayhi wa-sallam',
    'B9085 - Tadhyīl Sulāfat al-ʿAṣr',
    'B9086 - Fatḥ al-Raḥmān bi-Kashf mā Yaltabis fī al-Qurʾān',
    'B9087 - Fatāwá Yasʾalūnaka',
    'B9088 - Juzʾ Abī al-Jahm',
    'B9089 - al-Wasāʾil al-Mufīdah li-al-Ḥayāh al-Saʿīdah',
    'B9091 - Mirʾāt al-Jinān wa-ʿIbrat al-Yaqẓān',
    'B9092 - al-ʿAqāʾid al-Islāmīyah li-Ibn Bādīs',
    'B9093 - al-Anwāʾ fī Mawāsim al-ʿArab li-Ibn Qutaybah al-Dīnawarī',
    'B9096 - al-Majmūʿ al-Lafīf',
    'B9097 - Lamasāt bayānīyah fī nuṣūṣ min al-tanzīl - kitāb',
    'B9098 - Naẓm al-Durar fī Tanāsub al-Āyāt wa-al-Suwar',
    'B9099 - al-Muḥāḍarāt wa-al-Muḥāwarāt',
    'B9100 - al-Muqtaṭaf min Azāhir al-Ṭaraf',
    'B9102 - al-Zahr al-Fāʾiḥ fī Dhikr man Tanazzaha ʿan al-Dhunūb wa-al-Qabāʾiḥ',
    'B9103 - Bughyat al-Mutaṭawwiʿ fī Ṣalāt al-Taṭawwuʿ',
    'B9105 - al-Takmīl limā Fāta Takhrījuhu min Irwāʾ al-Ghalīl',
    'B9106 - Juzʾ al-Qāḍī al-Ashnānī',
    'B9107 - al-Mukhalliṣīyāt',
    'B9108 - al-Lubāb fī ʿUlūm al-Kitāb',
    'B9109 - Mabādiʾ al-Uṣūl',
    'B9110 - Sharīʿat al-Qurʾān min Dalāʾil Iʿjāzih',
    'B9111 - Bulūgh al-Marām min Adillat al-Aḥkām - taḥqīq al-Zuhayrī',
    'B9112 - Ghāyat al-Wuṣūl fī Sharḥ Lubb al-Uṣūl',
    'B9118 - Mudhakkirātī al-Siyāsīyah',
    'B9133 - ʿAwdat al-Ḥijāb',
    'B9134 - Sharḥ Shudhūr al-Dhahab lil-Jawjarī',
    'B9140 - Āthār Ibn Bādīs',
    'B9160 - Amālī al-Qālī',
    'B9170 - al-Thiqāt lil-ʿIjlī - taḥqīq Qalʿajī',
    'B9182 - Tafsīr al-Imām al-Shāfiʿī',
    'B9196 - al-Āḥād wa-al-Mathānī li-Ibn Abī ʿĀṣim',
    'B9198 - Aṣnāf al-Maghrūrīn',
    'B9199 - Iktifāʾ al-Qanūʿ bimā huwa maṭbūʿ',
    'B9200 - Sharḥ Uṣūl Iʿtiqād Ahl al-Sunnah wa-al-Jamāʿah',
    'B9202 - al-Ḥijāb Sharīʿat Allāh fī al-Islām wa-al-Yahūdīyah wa-al-Naṣrānīyah',
    'B9208 - al-Ibil',
    'B9209 - al-Ajwibah al-Mufīdah li-Muhimmāt al-ʿAqīdah',
    'B9211 - al-Ishtiqāq',
    'B9212 - Juzʾ ʿAlī ibn Muḥammad al-Ḥumayrī',
    'B9214 - al-Bidaʿ al-Ḥawlīyah',
];

const main = async () => {
    const json = (await Bun.file(`${process.env.COMPILATION_FOLDER!}/shamela.json`).json()) as Compilation;
    const idToExcerpt: Record<string, Excerpt> = {};
    json.excerpts.forEach((e) => {
        idToExcerpt[e.id] = e;
    });

    lines.forEach((l) => {
        const [id, value] = l.split(' - ');
        const e = idToExcerpt[id];

        if (!e) {
            throw new Error(`Excerpt not found ${id}`);
        }

        e.text = value;
        e.translator = 900;
    });

    await Bun.write(`${process.env.COMPILATION_FOLDER}/shamela2.json`, JSON.stringify(json, null, 2));
};

if (import.meta.main) {
    await main();
}
