/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as PromptsRouteImport } from './app/prompts'
import { Route as BrowseRouteImport } from './app/_browse'
import { Route as BrowseIndexRouteImport } from './app/_browse/index'
import { Route as ApiMetaRouteImport } from './app/api/meta'
import { Route as BrowseValidRouteImport } from './app/_browse/valid'
import { Route as BrowseInvalidRouteImport } from './app/_browse/invalid'
import { Route as BrowseDashboardRouteImport } from './app/_browse/dashboard'
import { Route as BrowseAnalyticsRouteImport } from './app/_browse/analytics'
import { Route as BrowseTranslationsRouteRouteImport } from './app/_browse/translations/route'
import { Route as BrowseTranslationsIndexRouteImport } from './app/_browse/translations/index'
import { Route as ApiTranslationsValidateRouteImport } from './app/api/translations/validate'
import { Route as ApiTranslationsFilesRouteImport } from './app/api/translations/files'
import { Route as ApiTranslationsFileRouteImport } from './app/api/translations/file'
import { Route as ApiTranslationsDeleteRouteImport } from './app/api/translations/delete'
import { Route as ApiTranslationsAssistRouteImport } from './app/api/translations/assist'
import { Route as ApiTranslationsIdRouteImport } from './app/api/translations/$id'
import { Route as ApiDashboardStatsRouteImport } from './app/api/dashboard/stats'
import { Route as ApiConfigPathsRouteImport } from './app/api/config/paths'
import { Route as ApiCompilationPromptRouteImport } from './app/api/compilation/prompt'
import { Route as ApiCompilationExcerptsRouteImport } from './app/api/compilation/excerpts'
import { Route as BrowseTranslationsFileNameIdRouteImport } from './app/_browse/translations/$fileNameId'
import { Route as ApiCompilationExcerptsShiftRouteImport } from './app/api/compilation/excerpts/shift'
import { Route as ApiCompilationExcerptsPayloadRouteImport } from './app/api/compilation/excerpts/payload'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/_browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseRoute,
} as any)
const ApiMetaRoute = ApiMetaRouteImport.update({
  id: '/api/meta',
  path: '/api/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseValidRoute = BrowseValidRouteImport.update({
  id: '/valid',
  path: '/valid',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseInvalidRoute = BrowseInvalidRouteImport.update({
  id: '/invalid',
  path: '/invalid',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseDashboardRoute = BrowseDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseAnalyticsRoute = BrowseAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseTranslationsRouteRoute = BrowseTranslationsRouteRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseTranslationsIndexRoute = BrowseTranslationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseTranslationsRouteRoute,
} as any)
const ApiTranslationsValidateRoute = ApiTranslationsValidateRouteImport.update({
  id: '/api/translations/validate',
  path: '/api/translations/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationsFilesRoute = ApiTranslationsFilesRouteImport.update({
  id: '/api/translations/files',
  path: '/api/translations/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationsFileRoute = ApiTranslationsFileRouteImport.update({
  id: '/api/translations/file',
  path: '/api/translations/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationsDeleteRoute = ApiTranslationsDeleteRouteImport.update({
  id: '/api/translations/delete',
  path: '/api/translations/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationsAssistRoute = ApiTranslationsAssistRouteImport.update({
  id: '/api/translations/assist',
  path: '/api/translations/assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationsIdRoute = ApiTranslationsIdRouteImport.update({
  id: '/api/translations/$id',
  path: '/api/translations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigPathsRoute = ApiConfigPathsRouteImport.update({
  id: '/api/config/paths',
  path: '/api/config/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompilationPromptRoute = ApiCompilationPromptRouteImport.update({
  id: '/api/compilation/prompt',
  path: '/api/compilation/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompilationExcerptsRoute = ApiCompilationExcerptsRouteImport.update({
  id: '/api/compilation/excerpts',
  path: '/api/compilation/excerpts',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseTranslationsFileNameIdRoute =
  BrowseTranslationsFileNameIdRouteImport.update({
    id: '/$fileNameId',
    path: '/$fileNameId',
    getParentRoute: () => BrowseTranslationsRouteRoute,
  } as any)
const ApiCompilationExcerptsShiftRoute =
  ApiCompilationExcerptsShiftRouteImport.update({
    id: '/shift',
    path: '/shift',
    getParentRoute: () => ApiCompilationExcerptsRoute,
  } as any)
const ApiCompilationExcerptsPayloadRoute =
  ApiCompilationExcerptsPayloadRouteImport.update({
    id: '/payload',
    path: '/payload',
    getParentRoute: () => ApiCompilationExcerptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof BrowseIndexRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/translations': typeof BrowseTranslationsRouteRouteWithChildren
  '/analytics': typeof BrowseAnalyticsRoute
  '/dashboard': typeof BrowseDashboardRoute
  '/invalid': typeof BrowseInvalidRoute
  '/valid': typeof BrowseValidRoute
  '/api/meta': typeof ApiMetaRoute
  '/translations/$fileNameId': typeof BrowseTranslationsFileNameIdRoute
  '/api/compilation/excerpts': typeof ApiCompilationExcerptsRouteWithChildren
  '/api/compilation/prompt': typeof ApiCompilationPromptRoute
  '/api/config/paths': typeof ApiConfigPathsRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/translations/$id': typeof ApiTranslationsIdRoute
  '/api/translations/assist': typeof ApiTranslationsAssistRoute
  '/api/translations/delete': typeof ApiTranslationsDeleteRoute
  '/api/translations/file': typeof ApiTranslationsFileRoute
  '/api/translations/files': typeof ApiTranslationsFilesRoute
  '/api/translations/validate': typeof ApiTranslationsValidateRoute
  '/translations/': typeof BrowseTranslationsIndexRoute
  '/api/compilation/excerpts/payload': typeof ApiCompilationExcerptsPayloadRoute
  '/api/compilation/excerpts/shift': typeof ApiCompilationExcerptsShiftRoute
}
export interface FileRoutesByTo {
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/analytics': typeof BrowseAnalyticsRoute
  '/dashboard': typeof BrowseDashboardRoute
  '/invalid': typeof BrowseInvalidRoute
  '/valid': typeof BrowseValidRoute
  '/api/meta': typeof ApiMetaRoute
  '/': typeof BrowseIndexRoute
  '/translations/$fileNameId': typeof BrowseTranslationsFileNameIdRoute
  '/api/compilation/excerpts': typeof ApiCompilationExcerptsRouteWithChildren
  '/api/compilation/prompt': typeof ApiCompilationPromptRoute
  '/api/config/paths': typeof ApiConfigPathsRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/translations/$id': typeof ApiTranslationsIdRoute
  '/api/translations/assist': typeof ApiTranslationsAssistRoute
  '/api/translations/delete': typeof ApiTranslationsDeleteRoute
  '/api/translations/file': typeof ApiTranslationsFileRoute
  '/api/translations/files': typeof ApiTranslationsFilesRoute
  '/api/translations/validate': typeof ApiTranslationsValidateRoute
  '/translations': typeof BrowseTranslationsIndexRoute
  '/api/compilation/excerpts/payload': typeof ApiCompilationExcerptsPayloadRoute
  '/api/compilation/excerpts/shift': typeof ApiCompilationExcerptsShiftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_browse': typeof BrowseRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/_browse/translations': typeof BrowseTranslationsRouteRouteWithChildren
  '/_browse/analytics': typeof BrowseAnalyticsRoute
  '/_browse/dashboard': typeof BrowseDashboardRoute
  '/_browse/invalid': typeof BrowseInvalidRoute
  '/_browse/valid': typeof BrowseValidRoute
  '/api/meta': typeof ApiMetaRoute
  '/_browse/': typeof BrowseIndexRoute
  '/_browse/translations/$fileNameId': typeof BrowseTranslationsFileNameIdRoute
  '/api/compilation/excerpts': typeof ApiCompilationExcerptsRouteWithChildren
  '/api/compilation/prompt': typeof ApiCompilationPromptRoute
  '/api/config/paths': typeof ApiConfigPathsRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/translations/$id': typeof ApiTranslationsIdRoute
  '/api/translations/assist': typeof ApiTranslationsAssistRoute
  '/api/translations/delete': typeof ApiTranslationsDeleteRoute
  '/api/translations/file': typeof ApiTranslationsFileRoute
  '/api/translations/files': typeof ApiTranslationsFilesRoute
  '/api/translations/validate': typeof ApiTranslationsValidateRoute
  '/_browse/translations/': typeof BrowseTranslationsIndexRoute
  '/api/compilation/excerpts/payload': typeof ApiCompilationExcerptsPayloadRoute
  '/api/compilation/excerpts/shift': typeof ApiCompilationExcerptsShiftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prompts'
    | '/settings'
    | '/translations'
    | '/analytics'
    | '/dashboard'
    | '/invalid'
    | '/valid'
    | '/api/meta'
    | '/translations/$fileNameId'
    | '/api/compilation/excerpts'
    | '/api/compilation/prompt'
    | '/api/config/paths'
    | '/api/dashboard/stats'
    | '/api/translations/$id'
    | '/api/translations/assist'
    | '/api/translations/delete'
    | '/api/translations/file'
    | '/api/translations/files'
    | '/api/translations/validate'
    | '/translations/'
    | '/api/compilation/excerpts/payload'
    | '/api/compilation/excerpts/shift'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/prompts'
    | '/settings'
    | '/analytics'
    | '/dashboard'
    | '/invalid'
    | '/valid'
    | '/api/meta'
    | '/'
    | '/translations/$fileNameId'
    | '/api/compilation/excerpts'
    | '/api/compilation/prompt'
    | '/api/config/paths'
    | '/api/dashboard/stats'
    | '/api/translations/$id'
    | '/api/translations/assist'
    | '/api/translations/delete'
    | '/api/translations/file'
    | '/api/translations/files'
    | '/api/translations/validate'
    | '/translations'
    | '/api/compilation/excerpts/payload'
    | '/api/compilation/excerpts/shift'
  id:
    | '__root__'
    | '/_browse'
    | '/prompts'
    | '/settings'
    | '/_browse/translations'
    | '/_browse/analytics'
    | '/_browse/dashboard'
    | '/_browse/invalid'
    | '/_browse/valid'
    | '/api/meta'
    | '/_browse/'
    | '/_browse/translations/$fileNameId'
    | '/api/compilation/excerpts'
    | '/api/compilation/prompt'
    | '/api/config/paths'
    | '/api/dashboard/stats'
    | '/api/translations/$id'
    | '/api/translations/assist'
    | '/api/translations/delete'
    | '/api/translations/file'
    | '/api/translations/files'
    | '/api/translations/validate'
    | '/_browse/translations/'
    | '/api/compilation/excerpts/payload'
    | '/api/compilation/excerpts/shift'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BrowseRoute: typeof BrowseRouteWithChildren
  PromptsRoute: typeof PromptsRoute
  SettingsRoute: typeof SettingsRoute
  ApiMetaRoute: typeof ApiMetaRoute
  ApiCompilationExcerptsRoute: typeof ApiCompilationExcerptsRouteWithChildren
  ApiCompilationPromptRoute: typeof ApiCompilationPromptRoute
  ApiConfigPathsRoute: typeof ApiConfigPathsRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiTranslationsIdRoute: typeof ApiTranslationsIdRoute
  ApiTranslationsAssistRoute: typeof ApiTranslationsAssistRoute
  ApiTranslationsDeleteRoute: typeof ApiTranslationsDeleteRoute
  ApiTranslationsFileRoute: typeof ApiTranslationsFileRoute
  ApiTranslationsFilesRoute: typeof ApiTranslationsFilesRoute
  ApiTranslationsValidateRoute: typeof ApiTranslationsValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse': {
      id: '/_browse'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse/': {
      id: '/_browse/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/api/meta': {
      id: '/api/meta'
      path: '/api/meta'
      fullPath: '/api/meta'
      preLoaderRoute: typeof ApiMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse/valid': {
      id: '/_browse/valid'
      path: '/valid'
      fullPath: '/valid'
      preLoaderRoute: typeof BrowseValidRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/invalid': {
      id: '/_browse/invalid'
      path: '/invalid'
      fullPath: '/invalid'
      preLoaderRoute: typeof BrowseInvalidRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/dashboard': {
      id: '/_browse/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof BrowseDashboardRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/analytics': {
      id: '/_browse/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof BrowseAnalyticsRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/translations': {
      id: '/_browse/translations'
      path: '/translations'
      fullPath: '/translations'
      preLoaderRoute: typeof BrowseTranslationsRouteRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/translations/': {
      id: '/_browse/translations/'
      path: '/'
      fullPath: '/translations/'
      preLoaderRoute: typeof BrowseTranslationsIndexRouteImport
      parentRoute: typeof BrowseTranslationsRouteRoute
    }
    '/api/translations/validate': {
      id: '/api/translations/validate'
      path: '/api/translations/validate'
      fullPath: '/api/translations/validate'
      preLoaderRoute: typeof ApiTranslationsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translations/files': {
      id: '/api/translations/files'
      path: '/api/translations/files'
      fullPath: '/api/translations/files'
      preLoaderRoute: typeof ApiTranslationsFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translations/file': {
      id: '/api/translations/file'
      path: '/api/translations/file'
      fullPath: '/api/translations/file'
      preLoaderRoute: typeof ApiTranslationsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translations/delete': {
      id: '/api/translations/delete'
      path: '/api/translations/delete'
      fullPath: '/api/translations/delete'
      preLoaderRoute: typeof ApiTranslationsDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translations/assist': {
      id: '/api/translations/assist'
      path: '/api/translations/assist'
      fullPath: '/api/translations/assist'
      preLoaderRoute: typeof ApiTranslationsAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translations/$id': {
      id: '/api/translations/$id'
      path: '/api/translations/$id'
      fullPath: '/api/translations/$id'
      preLoaderRoute: typeof ApiTranslationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config/paths': {
      id: '/api/config/paths'
      path: '/api/config/paths'
      fullPath: '/api/config/paths'
      preLoaderRoute: typeof ApiConfigPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compilation/prompt': {
      id: '/api/compilation/prompt'
      path: '/api/compilation/prompt'
      fullPath: '/api/compilation/prompt'
      preLoaderRoute: typeof ApiCompilationPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compilation/excerpts': {
      id: '/api/compilation/excerpts'
      path: '/api/compilation/excerpts'
      fullPath: '/api/compilation/excerpts'
      preLoaderRoute: typeof ApiCompilationExcerptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse/translations/$fileNameId': {
      id: '/_browse/translations/$fileNameId'
      path: '/$fileNameId'
      fullPath: '/translations/$fileNameId'
      preLoaderRoute: typeof BrowseTranslationsFileNameIdRouteImport
      parentRoute: typeof BrowseTranslationsRouteRoute
    }
    '/api/compilation/excerpts/shift': {
      id: '/api/compilation/excerpts/shift'
      path: '/shift'
      fullPath: '/api/compilation/excerpts/shift'
      preLoaderRoute: typeof ApiCompilationExcerptsShiftRouteImport
      parentRoute: typeof ApiCompilationExcerptsRoute
    }
    '/api/compilation/excerpts/payload': {
      id: '/api/compilation/excerpts/payload'
      path: '/payload'
      fullPath: '/api/compilation/excerpts/payload'
      preLoaderRoute: typeof ApiCompilationExcerptsPayloadRouteImport
      parentRoute: typeof ApiCompilationExcerptsRoute
    }
  }
}

interface BrowseTranslationsRouteRouteChildren {
  BrowseTranslationsFileNameIdRoute: typeof BrowseTranslationsFileNameIdRoute
  BrowseTranslationsIndexRoute: typeof BrowseTranslationsIndexRoute
}

const BrowseTranslationsRouteRouteChildren: BrowseTranslationsRouteRouteChildren =
  {
    BrowseTranslationsFileNameIdRoute: BrowseTranslationsFileNameIdRoute,
    BrowseTranslationsIndexRoute: BrowseTranslationsIndexRoute,
  }

const BrowseTranslationsRouteRouteWithChildren =
  BrowseTranslationsRouteRoute._addFileChildren(
    BrowseTranslationsRouteRouteChildren,
  )

interface BrowseRouteChildren {
  BrowseTranslationsRouteRoute: typeof BrowseTranslationsRouteRouteWithChildren
  BrowseAnalyticsRoute: typeof BrowseAnalyticsRoute
  BrowseDashboardRoute: typeof BrowseDashboardRoute
  BrowseInvalidRoute: typeof BrowseInvalidRoute
  BrowseValidRoute: typeof BrowseValidRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseTranslationsRouteRoute: BrowseTranslationsRouteRouteWithChildren,
  BrowseAnalyticsRoute: BrowseAnalyticsRoute,
  BrowseDashboardRoute: BrowseDashboardRoute,
  BrowseInvalidRoute: BrowseInvalidRoute,
  BrowseValidRoute: BrowseValidRoute,
  BrowseIndexRoute: BrowseIndexRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

interface ApiCompilationExcerptsRouteChildren {
  ApiCompilationExcerptsPayloadRoute: typeof ApiCompilationExcerptsPayloadRoute
  ApiCompilationExcerptsShiftRoute: typeof ApiCompilationExcerptsShiftRoute
}

const ApiCompilationExcerptsRouteChildren: ApiCompilationExcerptsRouteChildren =
  {
    ApiCompilationExcerptsPayloadRoute: ApiCompilationExcerptsPayloadRoute,
    ApiCompilationExcerptsShiftRoute: ApiCompilationExcerptsShiftRoute,
  }

const ApiCompilationExcerptsRouteWithChildren =
  ApiCompilationExcerptsRoute._addFileChildren(
    ApiCompilationExcerptsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  BrowseRoute: BrowseRouteWithChildren,
  PromptsRoute: PromptsRoute,
  SettingsRoute: SettingsRoute,
  ApiMetaRoute: ApiMetaRoute,
  ApiCompilationExcerptsRoute: ApiCompilationExcerptsRouteWithChildren,
  ApiCompilationPromptRoute: ApiCompilationPromptRoute,
  ApiConfigPathsRoute: ApiConfigPathsRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiTranslationsIdRoute: ApiTranslationsIdRoute,
  ApiTranslationsAssistRoute: ApiTranslationsAssistRoute,
  ApiTranslationsDeleteRoute: ApiTranslationsDeleteRoute,
  ApiTranslationsFileRoute: ApiTranslationsFileRoute,
  ApiTranslationsFilesRoute: ApiTranslationsFilesRoute,
  ApiTranslationsValidateRoute: ApiTranslationsValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
